[[part]]
ref = "V1"
x = 0.0
y = 0.0
rotation = 90
flip = false

[[part]]
ref = "VCC"
x = 40.0
y = 0.0
rotation = 90
flip = false

[[part]]
ref = "VEE"
x = 80.0
y = 0.0
rotation = 90
flip = false

[[part]]
ref = "X1"
x = 120.0
y = 0.0
rotation = 90
flip = false

[[part]]
ref = "CIN"
x = 160.0
y = 0.0
rotation = 0
flip = false

[[part]]
ref = "R1"
x = 200.0
y = 0.0
rotation = 0
flip = false

[[part]]
ref = "RV1_1"
x = 0.0
y = 40.0
rotation = 0
flip = false

[[part]]
ref = "RV1_2"
x = 40.0
y = 40.0
rotation = 0
flip = false

[[part]]
ref = "R2"
x = 80.0
y = 40.0
rotation = 0
flip = false

[[part]]
ref = "C1"
x = 120.0
y = 40.0
rotation = 0
flip = false

[[part]]
ref = "C2"
x = 160.0
y = 40.0
rotation = 0
flip = false

[[part]]
ref = "R3"
x = 200.0
y = 40.0
rotation = 0
flip = false

[[part]]
ref = "CT1"
x = 0.0
y = 80.0
rotation = 0
flip = false

[[part]]
ref = "RV2_1"
x = 40.0
y = 80.0
rotation = 0
flip = false

[[part]]
ref = "RV2_2"
x = 80.0
y = 80.0
rotation = 0
flip = false

[[part]]
ref = "CT2"
x = 120.0
y = 80.0
rotation = 0
flip = false

[[part]]
ref = "COUT"
x = 160.0
y = 80.0
rotation = 0
flip = false

[[part]]
ref = "RL"
x = 200.0
y = 80.0
rotation = 90
flip = false
