<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ssp</AssemblyName>
    <RootNamespace>Ssp.Cli</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ssp</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ssp.Core\Ssp.Core.csproj" />
  </ItemGroup>
</Project>
